# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Accidental Engineer
email: clive.shirley@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Documenting thinking and exploration into development practices, pitfalls and fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://macberrypro.com" # the base hostname & protocol for your site
twitter_username: macberrypro
github_username: cshirley

# Build settings
markdown: kramdown
