# Site settings
title: Aide Memoir [ ..for an ageing engineer]
email: clive@shirleyconsulting.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Coding and problem solving topics,
url: "http://macberrypro.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

github: cshirley
twitter: macberrypro
facebook:
instagram: macberrypro
dribbble:
google_plus:

# Build settings
markdown: kramdown

collections:
  projects:
    output: true

comments:
  disqus:
    short_name: macberryprocom

analytics:
  googleUA:
    tracking_id: UA-58277687-1

include:
  - _pages

compress_html:
  clippings: []
  blanklines: false
  comments: all
